version: '3.8'

networks:
  cluster-b:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.200.0/24

  shared-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24

services:
  # Master container in Cluster B
  container-b-master:
    container_name: cluster-b-master
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
      - shared-network
    ipv4_address: 192.168.200.2
    volumes:
      - ./multicast_sender.py:/multicast_sender.py  # Mount the multicast sender script

  # Client containers (7 clients)
  container-b2:
    container_name: project1-container-b2
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.3
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b3:
    container_name: project1-container-b3
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.4
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b4:
    container_name: project1-container-b4
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.5
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b5:
    container_name: project1-container-b5
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.6
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b6:
    container_name: project1-container-b6
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.7
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b7:
    container_name: project1-container-b7
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.8
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script

  container-b8:
    container_name: project1-container-b8
    image: python:3.9
    command: tail -f /dev/null  # Keeps the container running
    networks:
      - cluster-b
    ipv4_address: 192.168.200.9
    volumes:
      - ./multicast_receiver.py:/multicast_receiver.py  # Mount the multicast receiver script
