#version: '3.8'

services:
  # Master Cluster A
  broadcast_sender:
    image: python:3.9
    container_name: broadcast_sender
    networks:
      cluster_a:
        ipv4_address: 192.168.0.2
    volumes:
      - ./broadcast_sender.py:/broadcast_sender.py
    command: ["python", "/broadcast_sender.py"]
    privileged: true

  container_1:
    image: python:3.9
    container_name: container_1
    networks:
      cluster_a:
        ipv4_address: 192.168.0.3
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_2:
    image: python:3.9
    container_name: container_2
    networks:
      cluster_a:
        ipv4_address: 192.168.0.4
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_3:
    image: python:3.9
    container_name: container_3
    networks:
      cluster_a:
        ipv4_address: 192.168.0.5
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_4:
    image: python:3.9
    container_name: container_4
    networks:
      cluster_a:
        ipv4_address: 192.168.0.6
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_5:
    image: python:3.9
    container_name: container_5
    networks:
      cluster_a:
        ipv4_address: 192.168.0.7
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_6:
    image: python:3.9
    container_name: container_6
    networks:
      cluster_a:
        ipv4_address: 192.168.0.8
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  container_7:
    image: python:3.9
    container_name: container_7
    networks:
      cluster_a:
        ipv4_address: 192.168.0.9
    volumes:
      - ./broadcast_reciever.py:/broadcast_reciever.py
    command: ["python", "/broadcast_reciever.py"]

  # Master Cluster B (No command, no python script)
  master_cluster_b:
    image: python:3.9
    container_name: master_cluster_b
    networks:
      cluster_b:
        ipv4_address: 192.169.0.2
    volumes:
      - ./multicast_sender.py:/multicast_sender.py
    command: ["python", "/multicast_sender.py", "224.1.1.1"]  # Send only to first half

  # First half of the receivers (Listening on 224.1.1.1)
  container_8:
    image: python:3.9
    container_name: container_8
    networks:
      cluster_b:
        ipv4_address: 192.169.0.3
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.1"]

  container_9:
    image: python:3.9
    container_name: container_9
    networks:
      cluster_b:
        ipv4_address: 192.169.0.4
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.1"]

  container_10:
    image: python:3.9
    container_name: container_10
    networks:
      cluster_b:
        ipv4_address: 192.169.0.5
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.1"]

  container_11:
    image: python:3.9
    container_name: container_11
    networks:
      cluster_b:
        ipv4_address: 192.169.0.6
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.1"]

  # Second half of the receivers (Listening on 224.1.1.2, ignored by sender)
  container_12:
    image: python:3.9
    container_name: container_12
    networks:
      cluster_b:
        ipv4_address: 192.169.0.7
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.2"]

  container_13:
    image: python:3.9
    container_name: container_13
    networks:
      cluster_b:
        ipv4_address: 192.169.0.8
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.2"]

  container_14:
    image: python:3.9
    container_name: container_14
    networks:
      cluster_b:
        ipv4_address: 192.169.0.9
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.2"]

  container_15:
    image: python:3.9
    container_name: container_15
    networks:
      cluster_b:
        ipv4_address: 192.169.0.10
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.2"]

  container_16:
    image: python:3.9
    container_name: container_16
    networks:
      cluster_b:
        ipv4_address: 192.169.0.11
    volumes:
      - ./multicast_reciever.py:/multicast_reciever.py
    command: ["python", "/multicast_reciever.py", "224.1.1.2"]


  network_monitor:
    build: .
    image: cecs327-project-1-network_monitor
    container_name: network_monitor
    networks:
      - cluster_a
      - cluster_b
    volumes:
      - ./logs:/app/logs
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    command: ["python", "/app/monitor.py"]


networks:
  cluster_a:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"

  cluster_b:
    driver: bridge
    ipam:
      config:
        - subnet: "192.169.0.0/24"